import "./globals.css";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-full bg-gray-50">
        <body className="h-full">{children}</body>
      </html>
    </SessionProvider>
  );
}
