import { TopNavigationBar } from "@/components/TopNavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "@/components/Sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`h-full bg-white ${inter.className}`}>
      <body className="h-full">
        <div className="h-full lg:grid lg:grid-cols-[18rem_1fr]">
          <Sidebar />
          <div>
            <TopNavigationBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
