import { TopNavigationBar } from "@/components/TopNavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "@/components/Sidebar";
import { getServerSession } from "next-auth";
import { NEXT_AUTH_HANDLER_OPTIONS } from "@/lib/features/next-auth";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(NEXT_AUTH_HANDLER_OPTIONS);

  console.log("SESSION", session);

  return (
    <html lang="en" className={`h-full bg-white ${inter.className}`}>
      <body className="h-full">
        <div className="h-full lg:grid lg:grid-cols-[14rem_1fr]">
          <Sidebar session={session} />
          <div>
            <TopNavigationBar session={session} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
